version: '3.5'

services:
  node:
    build:
      dockerfile: Dockerfile
    image: vocaltime:tag
    volumes:
      - type: bind
        source: /home/krist/bots/VocalTimeCounter/prisma
        target: /prisma